- codec.go
- codec_test.go
- messagequeue_test.go
- receiver.go
* decompressor would fail on compressed zero-length data (a single 00
byte.) Fixed by moving the checksum test to the top of the loop.
* Simplified the checksum test and moved into 'for' statement.
* decompressor now uses the Context to log, so client can see the
errors.
* Added a few comments.
* Restore testing entire range of frame sizes 0..65535 with
TestCompressDecompressManySizes (without creating a bajillion
goroutines)
* Added silent mode and counter to TestLogContext
* Suppress error logs from TestDecompressInvalidInput and
TestDecompressInvalidChecksum
* Suppress progress logs in messagequeue_test.go
> Fixed zero-length decompress, improved logging, improved tests

- context.go
- sender.go
Fixes https://github.com/couchbase/sync_gateway/issues/3232
1. Adds context id to blip context
1. Removes unnecessary "..." from a few logs
1. Lowercases a few log messages.  Eg, "INCOMING MESSAGE" -> "Incoming Message"
1. Rename `fmt` -> `format` to avoid go package name collisions
> Fixes SG #3232 prefix unique id to go-blip logs

- message.go
https://github.com/couchbase/sync_gateway/issues/3255 Recover from panic inside Message asyncRead and nextFrameToSend goroutines
> Add recover in Message asyncRead and nextFrameToSend goroutines

- context.go
- context_test.go
- expvar.go
- message.go
- messagequeue.go
- receiver.go
- sender.go
Fixes https://github.com/couchbase/go-blip/issues/17
Fixes https://github.com/couchbase/sync_gateway/issues/3268
Changes:
- Add go-blip tests to detect issues originally seen in https://github.com/couchbase/sync_gateway/issues/3268.  
- Add expvars to instrument go-blip related goroutines, to help identify resource leaks
- Fix underlying issue that caused tests added in this PR to block indefinitely -- in `sender.stop()`, see the code added `for _, msgStreamer := range sender.receiver.pendingResponses {...}`
> PR: BLIP client blocks indefinitely when peer abruptly closes connection

- context.go
- context_test.go
- example/cmd/responder.go
- example/cmd/sendtest.go
- functional_test.go
- protocol.go
> Fixes #24 Update WebSocket protocol to “BLIP_3"

- receiver.go
It's misleading when it says "Error decompressing", even if compression is disabled.
> Update the logging wording when it has an error

- message.go
Preserves number formatting when unmarshalling numbers to interface{}.
Part of fix for https://github.com/couchbase/sync_gateway/issues/3783
> Set UseNumber when decoding message bodies

- .drone.yml
- Jenkinsfile
- messagequeue.go
- receiver.go
Cherry picks #34, #36, #37, and #39 to the `sync_gateway-2.1.x` branch
(everything on `master` except the `json.Number` fix (#35))
This is to get CBG-279 backported to SG 2.1.4 without including the `json.Number` fixes.
> CBG-279 Cherry pick all except json.Number PRs into SG 2.1.x branch

- message.go
- messagequeue.go
- messagequeue_test.go
- sender.go
When sending a message over BLIP, and that message is large enough to span multiple frames, `nextFrameToSend()` leaks its encoder writer goroutine and it never unblocks on `m.WriteTo()` when `sender.conn.Write()` errors in the main BLIP sender loop.
This can be seen in the expvars, as goblip.goroutines_next_frame_to_send:93, and observed in goroutine profiles
Changes
=======
- Switch `Message.encoder` to be a `ReadCloser` interface.
- Add `Message.Close()` method to close both underlying message reader and message encoder.
- Call `Message.Close()` when the sender encounters an error sending a frame over the network.
- Switch `messageQueue.Stop()` to use `message.Close()`
> CBG-279 Fix leak in nextFrameToSend by closing message encoder

- message.go
- messagequeue.go
- messagequeue_test.go
- sender.go
Backports CBG-279 Fix leak in nextFrameToSend by closing message encoder (#38)
* CBG-279 Fix leak in nextFrameToSend by closing message encoder
When aborting sending a message over BLIP, and that message is large enough to span multiple frames,
nextFrameToSend leaks its encoder writer goroutine and it never unblocks on m.WriteTo()
This can be seen in the expvars, as goblip.goroutines_next_frame_to_send:93, and observed in goroutine profiles
Changes
=======
- Make blip.Message.encoder a ReadCloser
- Add blip.Message.Close() method to close both message reader and message encoder.
* Use ioutil.NopCloser for test encoder
* Return error from message.Close()
> Backport #38 to SG 2.1.x branch

- context.go
- expvar.go
- functional_test.go
- sender.go
If the blip.Context's `WebsocketPingInterval` duration is non-zero, it spawns an additional sender goroutine, and periodically sends Websocket Ping frames.
> Add WebsocketPingInterval option

- Jenkinsfile
- context.go
- context_test.go
- example/cmd/responder.go
- example/cmd/sendtest.go
- functional_test.go
- protocol.go
Allows multiple protocols to be passed in when creating a NewContext. This means a host can specify multiple supported versions allowing sub protocols to be updated whilst still being backwards compatible for older clients.
For hosts NewContext should have subprotocols passed in which it can support.
For clients NewContext should have subprotocols passed in which it can support but should be ordered so that the preferred method is first.
ActiveProtocol returns the protocol set in the format passed in (doesn't have the BLIPV3 tagged onto it).
> CBG-1435: Allow multiple protocols to be supported

- context.go
- protocol.go
ActiveProtocol is a relatively expensive call (it's doing strings.SplitN every time), so it sounds reasonable to store the currently used Websocket subprotocol on BLIP context.
> CBG-1517 Store the currently used Websocket subprotocol on BLIP context

- context.go
- context_test.go
Changes to rename ActiveProtocol to ActiveSubprotocol.
> CBG-1517 Rename ActiveProtocol to ActiveSubprotocol

- context.go
- context_test.go
- example/cmd/responder.go
- example/cmd/sendtest.go
- functional_test.go
- properties_test.go
- receiver.go
- sender.go
- `Context.Dial()` now accepts only one parameter (the URL)
- `Context.DialConfig()` now accepts a `DialOptions` struct, rather than a library-specific implementation.
- `Context.WebSocketServer()` returns a generic HTTP handler, rather than a library-specific implementation.
> Replace x/net/websocket library with nhooyr.io/websocket

- codec.go
- go.mod
- go.sum
Not only does it claim to be optimized, it does not appear to suffer from the same bug as the std one does (see JIRA for more info)
> CBG-1712: Replaced std compress/flate with third party

- context.go
- receiver.go
The old websocket library used `io.EOF` to signal websocket closures, as it could not handle status codes.
The new library does not use `io.EOF`, and we need to check the close handshake status to continue conditionally logging close messages.
> Add isCloseError helper and use it to lower log level of expected close 'errors'

- context.go
- receiver.go
- sender.go
Use separate stats for reciever and sender, the idea is to have minimal locking so sync gateway can consume this data.
> Add bytes transferred stat

- context.go
Allows consumers (SG) to be notified that the websocket upgrade and subprotocol handshake are done.
Example usage:
```go
// Create a BLIP WebSocket handler and have it handle the request:
server := blipContext.WebSocketServer()
go func() {
if ok := server.WaitUntilStarted(h.ctx()); !ok {
base.InfofCtx(h.ctx(), base.KeyHTTP, "BLIP+WebSocket connection closed before upgrade")
return
}
subprotocol := blipContext.ActiveSubprotocol()
h.logStatus(http.StatusSwitchingProtocols, fmt.Sprintf("[%s] Upgraded to WebSocket protocol %s+%s%s", blipContext.ID, blip.WebSocketSubProtocolPrefix, subprotocol, h.formattedEffectiveUserName()))
}()
```
> Add WaitUntilStarted() on BlipWebsocketServer

- context.go
- context_test.go
- functional_test.go
Enable checking the Origin header the websocket library. 
This works on top of https://github.com/couchbase/go-blip/pull/70.
Odd things about this code:
- Unlike how you pass `Origin` header, the websocket library expects hostnames without URLs, it matches on `u.Host`, so `example.com` instead of `wss://example.com` or `ws://example.com`. Other things that match `*` are allowed. This mostly has consequences in the Sync Gateway review, since we have to convert our structures.
- Because I added a `[]string` option to `NewContext` I changed the calling code to use an options struct since I keep messing up the API that was `NewContext(origin []string, protocols... string)`. I'm not committed to the API I picked at all, it was to prevent my mistakes.
> CBG-3652 check Origin header in websocket library

- context.go
- context_test.go
- functional_test.go
backports: CBG-3652 check Origin header in websocket library (https://github.com/couchbase/go-blip/pull/71)
> [3.1.3 backport]  CBG-3660 check Origin header in websocket library

- context.go
- Created `release/3.1.6` from `release/3.1.3`
- Clean cherry-pick of #64
> [3.1.6] CBG-3860: Unwrap errors for EOFs in `isCloseError`

- .github/workflows/ci.yml
- .golangci.yml
- use go 1.23.5 to match Sync Gateway
- update golangci-lint versions
- remove deprecated linters in .golanci.yml, only explicitly disable linters that are active
preparing to add some new code that using `atomic` package primitives and updating go.mod 1.23
> update golangci-lint/github workflows

- sender.go
- sender_test.go
`nextFrameToSend` will leak goroutines if docs are large enough to be split into multiple frames and the connection goes dead CBL side but our side its still alive causing blip to queue messages in a map called iceBox when you have so many frames associated with one messages not ack’d. Then when the connection is eventually torn down, sender.stop() will iterate through the queues messages and close each message in queue but will not iterate through the icebox map to close any messages in there. 
I was able to repro the leak see below:
The fix is to iterate through icebox map to close all messages in the map when the sender is closed. This will teardown any goroutines writing to pipe in `nextFrameToSend`
> CBG-4572: close all messages in iceBox map when sender is closed
